version: "3.9"

services:
  db:
    image: postgres:15-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: eth_ind
      POSTGRES_USER: eth_ind
      POSTGRES_PASSWORD: password
    volumes:
      - pgdata:/var/lib/postgresql/data

  eth-ind:
    build: .
    command: run service
    dns:
      - 8.8.8.8
      - 1.1.1.1
    depends_on:
      - db
    restart: on-failure
    ports:
      - "8000:8000" 
    #volumes:
      #- ./config.yaml:/config.yaml
    environment:
      - KV_VIPER_FILE=/config.yaml
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx-conf:/etc/nginx/conf.d
    ports:
      - "80:80"
    depends_on:
      - eth-ind
    environment:
      - NGINX_ENTRYPOINT_QUIET_LOGS=1

volumes:
  pgdata: